---

- name: Install and configure docker
  hosts: vms
  tasks:
    - name: Remove old packages
      package:
        name:
          - docker 
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent
    
    - name: Set up
      package:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest
    
    - name: Set up docker repo
      shell: >
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        && echo
        "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu 
        $(lsb_release -cs)" stable | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Install docker 
      package:
        name:
          - docker-ce 
          - docker-ce-cli
          - containerd.io
        state: latest


