apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:2.349-jdk11
        ports:
        - name: jenkins-web
          containerPort: 8080
          protocol: TCP
        - name: jnlp-port
          containerPort: 50000
      volumes:
        - name: jenkins-vol

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
    - name: jenkins-exposed
      protocol: TCP
      port: 8080
      targetPort: jenkins-web