apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:2.349-jdk11
        ports:
        - containerPort: 50000
        - containerPort: 8080
        - mountPath: /var/jenkins_home
          name: test-volume
      volumes:
      - name: jenkins-vol