apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app.kubernetes.io/name: jenkins
  ports:
  - name: jenkins-http-port-exposed
    protocol: TCP
    port: 80
    targetPort: jenkins-http-port

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app.kubernetes.io/name: jenkins
  ports:
  - name: jenkins-http-port-exposed
    protocol: TCP
    port: 80
    targetPort: jenkins-http-port